### ISSUE TITLE
Crash when trying to edit

### ISSUE THREAD

**Issue by LemADEC** [KaiKikuchi/BetterChunkLoader#10]
It seems the edit feature doesn't work due to title length:
```
[19:42:25 ERROR]: Could not pass event PlayerInteractEvent to BetterChunkLoader v2.2.2
org.bukkit.event.EventException
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1614.57]
>       at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:429) [mx.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861) [nh.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Title cannot be longer than 32 characters
>       at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[Validate.class:2.6]
>       at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventoryCustom$MinecraftInventory.<init>(CraftInventoryCustom.java:54) ~[CraftInventoryCustom$MinecraftInventory.class:1.7.10-1614.57]
>       at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventoryCustom.<init>(CraftInventoryCustom.java:27) ~[CraftInventoryCustom.class:1.7.10-1614.57]
>       at org.bukkit.craftbukkit.v1_7_R4.CraftServer.createInventory(CraftServer.java:1591) ~[CraftServer.class:1.7.10-1614.57]
>       at org.bukkit.Bukkit.createInventory(Bukkit.java:629) ~[Bukkit.class:1.7.10-1614.57]
>       at net.kaikk.mc.bcl.CChunkLoader.showUI(CChunkLoader.java:172) ~[?:?]
>       at net.kaikk.mc.bcl.EventListener.onPlayerInteract(EventListener.java:44) ~[?:?]
>       at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source) ~[?:?]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
>       ... 15 more
```

**Comment by KaiKikuchi** [comment]
I've actually fixed this a lot of time ago in v.2.3.2 (http://i.imgur.com/qZs8KLK.png), but I haven't updated the repository yet. I've upload just the jar file on my website, but not on Github releases.
