### ISSUE TITLE
Error when plugin is enabled

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/BetterChunkLoader#19]
When my server starts up, this following error appears in console:

```
[16:43:52 INFO]: [BetterChunkLoader] Enabling BetterChunkLoader v2.5
[16:43:52 INFO]: [BetterChunkLoader] Loading config...
[16:43:52 WARN]: java.lang.ClassCastException: net.kaikk.mc.bcl.datastore.MySqlDataStore cannot be cast to net.kaikk.mc.bcl.datastore.IDataStore
[16:43:52 WARN]:        at net.kaikk.mc.bcl.datastore.DataStoreManager.setDataStoreInstance(DataStoreManager.java:37)
[16:43:52 WARN]:        at net.kaikk.mc.bcl.BetterChunkLoader.enable(BetterChunkLoader.java:65)
[16:43:52 WARN]:        at net.kaikk.mc.bcl.BetterChunkLoader.onEnable(BetterChunkLoader.java:47)
[16:43:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[16:43:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[16:43:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[16:43:52 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363)
[16:43:52 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[16:43:52 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[16:43:52 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:43:52 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[16:43:52 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740)
[16:43:52 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:720)
[16:43:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:474)
[16:43:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:433)
[16:43:52 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[16:43:52 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[16:43:52 WARN]:        at java.lang.Thread.run(Thread.java:745)
[16:43:52 WARN]: [BetterChunkLoader] Load failed!
[16:43:52 INFO]: [BetterChunkLoader] Disabling BetterChunkLoader v2.5
```
Then the plugin disables itself.

**Comment by KaiKikuchi** [comment]
Restart your server when updating any plugin.

**Comment by Eufranio** [comment]
I did, it happens every time that the server is starting (and enabling the plugin).

**Comment by KaiKikuchi** [comment]
Then send the correct log. The log you posted shows you used plugman to enable the plugin. This is not a bcl issue because mysqldatastore can always be casted to idatastore. This issue usually means you replaced the plugin jar and didn't restart the server

**Comment by Eufranio** [comment]
I've searched and nothing shows up in the log, only the **Enabling BetterChunkLoader** message, and then this error. Happened since I changed the Always on Chunk Loader material in the config and restarted the server...

**Comment by Eufranio** [comment]
After a MySQL server the issue disappeared... Do you know what could be wrong?

**Comment by KaiKikuchi** [comment]
Sorry there is something missing in your sentence. Anyway i don't know. I think your server has some issue

**Comment by Eufranio** [comment]
RIP... Fresh install, needed to restart MySQL, the same way. Thanks for your help anyway.
